### ISSUE TITLE
Further explanation of Autoretrieve

### ISSUE THREAD

**Issue by Kevin-Mok** [application-research/autoretrieve#151]
I read the description in the README, but I'm not sure I fully understand it and its benefits. I am also new to the ecosystem so that contributes to my lack of understanding. Could there be further documentation somewhere to explain it? Possibly with explanations and references to relevant documentation such that I would be able to understand it?

**Comment by elijaharita** [comment]
started to add some more info with #152. anything more you'd like to be added?

**Comment by Kevin-Mok** [comment]
Resolved with #152.
