### ISSUE TITLE
per-provider rate limit

### ISSUE THREAD

**Issue by willscott** [application-research/autoretrieve#16]
we should be able to have a knob where we can limit how many concurrent / rate of data we pull from a given provider.

**Comment by elijaharita** [comment]
are you looking for `--per-miner-retrieval-limit`?

**Comment by willscott** [comment]
yep. eventually we'll want to be able to tune that on a per-miner basis, so e.g. default 10 but higher on some specific ones and lower on others.

**Comment by elijaharita** [comment]
ahh got it. any recommendations on how this would be configured?

**Comment by willscott** [comment]
just that when providers yell at us that we're making too many retrievals it seems better to put them on a list to make less retrievals rather than blocking them entirely.

maybe we make an admin server on a different port and i can make a request to /<provider>/rate to set it?
