### ISSUE TITLE
Automate a Docker Build System for the service

### ISSUE THREAD

**Issue by davidd8** [application-research/autoretrieve#21]
Currently, setting up the autoretrieve service on EC2 requires a lot of manual steps. Automate the steps to allow for CI/CD build systems and quick deploys.

**Comment by kylehuntsman** [comment]
I'm going to open this issue back up. We don't have CI/CD setup for quick deploys of branches. Ideally this is a system where we can push a commit to a branch, and have an autoretrieve instance automagically be spun up for that branch.

**Comment by aronchick** [comment]
can we overlap with the work the Weaveworks/Infrastructure team is doing? (e.g. i think it's under Mike Greenberg)
