### ISSUE TITLE
Launch scale deployment autoretrieve 

### ISSUE THREAD

**Issue by davidd8** [application-research/autoretrieve#27]
Once CID exclusion lists, datastore pruning, and real-time metrics are implemented, relaunch the autoretrieve service in production.

**Comment by davidd8** [comment]
@kylehuntsman can we close this ticket, as Autoretrieve is running and serving production traffic? We can make a subsequent ticket to track moving to gitops infrastructure.

**Comment by honghaoq** [comment]
@kylehuntsman has this been completed as autoretrieve is running in prod now - should we close this as done?
