### ISSUE TITLE
Monitor and adjust autoretrieve real-time metrics post-launch

### ISSUE THREAD

**Issue by davidd8** [application-research/autoretrieve#29]
Once in production, monitor the grafana dashboard to better understand autoretrieve patterns, and tune the dashboard as necessary. Other metrics to consider: number of cache hits vs. making a Filecoin retrieval. Performance comparison between cache and non-cache responses. etc.

**Comment by hannahhoward** [comment]
close as not having definitive scope and we are doing this on an ongoing basis.
